import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const font = Poppins({ subsets: ['latin'], weight: '400' });

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${font.className} container mx-auto py-12`}>
        <Toaster visibleToasts={1} richColors />
        {children}
      </body>
    </html>
  );
}
